---
- hosts: all
  gather_facts: no
  become: false
  tasks:
  - name: check NVIDIA driver modules are loaded
    shell: "lsmod | grep -i nvidia"
    register: nvidia_mod
    no_log: True
    failed_when: false
  - name: capture NVIDIA driver module loaded status
    when:  nvidia_mod.rc != 1
    ansible.builtin.set_fact:
      nvidia_mod_loaded: true
- hosts: localhost
  connection: local
  gather_facts: yes
  become: false
  tasks:
  - name: capture instances with nvidia mod
    ansible.builtin.set_fact:
      instances_with_nvidia_mod:
        "{{
          groups.all |
          map('extract', hostvars) |
          selectattr('nvidia_mod_loaded', 'defined') |
          selectattr('nvidia_mod_loaded', 'equalto', True) |
          map(attribute='nvidia_mod_loaded') |
          length
        }}"
    no_log: true
  - name: capture user intent to override driver
    when: instances_with_nvidia_mod | int > 0
    ansible.builtin.pause:
      prompt: "One or more hosts has NVIDIA driver installed. Do you want to override it (y/n)?"
    register: override_driver
  - name: capture override driver
    when: instances_with_nvidia_mod | int == 0 or override_driver.user_input == 'y'
    lineinfile:
      path: gpu-operator-values.yml
      regexp: '^install_driver:'
      line: 'install_driver: true'
  - name: capture override driver
    when: instances_with_nvidia_mod | int > 0 and override_driver.user_input != 'y'
    lineinfile:
      path: gpu-operator-values.yml
      regexp: '^install_driver:'
      line: 'install_driver: false'
